[package]
name = "folk-runtime-fork"
description = "Fork-based worker runtime for Folk — prefork master with warm OPcache"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dependencies]
folk-api = { git = "https://github.com/Folk-Project/folk-api" }
folk-core = { path = "../folk-core" }
folk-protocol = { path = "../folk-protocol" }
folk-runtime-pipe = { path = "../folk-runtime-pipe" }

tokio = { workspace = true }
tokio-util = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
rmpv = { workspace = true }
rmp-serde = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3"
rmpv = { workspace = true }
